version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt  # Pointing to the existing requirements file

sphinx:
  configuration: docs/conf.py  # Adjust if needed